final String FRAMEWORK_PREBUILTS_DIR = "prebuilts"

android {
    flavorDimensions "app", "ui"

    defaultConfig {
        testApplicationId 'dev.dworks.apps.alauncher.tests'
        versionName rootProject.generateVersionName()
        versionCode rootProject.generateVersionCode(1)
    }

    productFlavors {
        leewyn {
            dimension "app"
            applicationId "dev.dworks.apps.alauncher"
        }
        customUI {
            dimension "ui"
        }
    }

    sourceSets {
        leewyn {
            aidl.srcDirs = ['shade/aidl']
            assets.srcDirs = ['shade/assets']
            res.srcDirs = ['shade/res', 'shade/res_translations', 'shade/res_translations_manual']
            java.srcDirs = ['shade/src', 'shade/src_flags', 'src_shortcuts_overrides',
                            'shade/src_backport']
            manifest.srcFile "shade/AndroidManifest.xml"
        }
        customUI {
            res.srcDirs = ['shade/res_ui_overrides']
            java.srcDirs = ['shade/src_ui_overrides']
        }
    }

    dependencies {
        customUIImplementation fileTree(dir: "${FRAMEWORK_PREBUILTS_DIR}/libs", include: 'plugin_core.jar')
    }
}
